# Generated by Django 5.1.4 on 2025-02-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='time_taken',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
